dat_HPV <- list(Initiation = "Following WHO recommendation of single dose HPV schedule",
                Question = c(Q1 = "Should adolescents and young adults receive a single dose of 9vHPV compared to no vaccine/control vaccine/placebo?",                  Q2 = "Should adolescents and young adults receive a single dose of 9vHPV compared to two or three doses?"),
                Population = c(Q1 = "Immunocompetent children and adults over 9 years",
                               Q2 = "Immunocompetent children and adults over 9 years"),
                Intervention = c(Q1 = "1 dose 9vHPV",
                                 Q2 = "1 dose 9vHPV"),
                Comparator = c(Q1 = "No vaccine/control vaccine/placebo",
                               Q2 = "2 or 3 doses of 9vHPV"),
                Literature = c(Q1 = "One RCT and one observational",
                               Q2 = "Four RCTs"),
                Outcomes = list(Q1 = list(`Effectiveness against HPV infection at 18 months` =
                                            list(`Risk of Bias` = c(Rating = "Serious", Reason = "Missing outcome data"),
                                                 Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                 Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "None",
                                                 Certainty = "Moderate",
                                                 Direction = "Large benefit",
                                                 Importance = "Critical"),
                                          `Effectiveness against HPV infection at >18 months` =
                                            list(`Risk of Bias` = c(Rating = "Serious", Reason = "Missing outcome data"),
                                                 Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                 Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "None",
                                                 Certainty = "Moderate",
                                                 Direction = "Large benefit",
                                                 Importance = "Critical"),
                                          `Effectiveness against genital infection at 12 months` =
                                            list(`Risk of Bias` = c(Rating = "Serious", Reason = "Selection of reported results"),
                                                 Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                 Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "None",
                                                 Certainty = "Moderate",
                                                 Direction = "Moderate benefit",
                                                 Importance = "Critical"),
                                          `Effectiveness against CIN3+ infection at 24 months` =
                                            list(`Risk of Bias` = c(Rating = "Serious", Reason = "Selection of reported results"),
                                                 Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                 Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "None",
                                                 Certainty = "Moderate",
                                                 Direction = "Moderate benefit",
                                                 Importance = "Critical"),
                                          `Serious adverse events` =
                                            list(`Risk of Bias` = c(Rating = "Serious", Reason = "Missing outcome data"),
                                                 Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                 Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "None",
                                                 Certainty = "Moderate",
                                                 Direction = "Little to no difference",
                                                 Importance = "Critical")),
                                Q2 = list(`Effectiveness against genital infection at 12 months` =
                                            list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                 Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                 Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "None",
                                                 Certainty = "High",
                                                 Direction = "Little to no difference",
                                                 Importance = "Critical"),
                                          `Serious adverse events` =
                                            list(`Risk of Bias` = c(Rating = "Serious", Reason = "Selection of reported results"),
                                                 Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                 Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "None",
                                                 Certainty = "Moderate",
                                                 Direction = "Little to no difference",
                                                 Importance = "Critical"),
                                          `Seropositivity at 1 month` =
                                            list(`Risk of Bias` = c(Rating = "Serious", Reason = "No information on allocation concealment"),
                                                 Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                 Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "None",
                                                 Certainty = "Moderate",
                                                 Direction = "Little to no difference",
                                                 Importance = "Important"),
                                          `Seropositivity at 7 months` =
                                            list(`Risk of Bias` = c(Rating = "Serious", Reason = "Selection of reported results"),
                                                 Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                 Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "None",
                                                 Certainty = "Moderate",
                                                 Direction = "Little to no difference",
                                                 Importance = "Important"),
                                          `Seropositivity at 12 months` =
                                            list(`Risk of Bias` = c(Rating = "Serious", Reason = "Selection of reported results"),
                                                 Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                 Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "None",
                                                 Certainty = "Moderate",
                                                 Direction = "Little to no difference",
                                                 Importance = "Important"),
                                          `Seropositivity at 24 months` =
                                            list(`Risk of Bias` = c(Rating = "Serious", Reason = "Selection of reported results"),
                                                 Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                 Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "None",
                                                 Certainty = "Moderate",
                                                 Direction = "Little to no difference",
                                                 Importance = "Important"),
                                          `GMT ratio at 1 month` =
                                            list(`Risk of Bias` = c(Rating = "Serious", Reason = "No information on allocation concealment"),
                                                 Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                 Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "None",
                                                 Certainty = "Moderate",
                                                 Direction = "Moderate cost",
                                                 Importance = "Important"),
                                          `Local adverse events` =
                                            list(`Risk of Bias` = c(Rating = "Serious", Reason = "No information on allocation concealment"),
                                                 Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                 Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "None",
                                                 Certainty = "Moderate",
                                                 Direction = "Little to no difference",
                                                 Importance = "Important"),
                                          `Systemic adverse events` =
                                            list(`Risk of Bias` = c(Rating = "Serious", Reason = "No information on allocation concealment"),
                                                 Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                 Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "None",
                                                 Certainty = "Moderate",
                                                 Direction = "Little to no difference",
                                                 Importance = "Important"))),
                `Evidence to decision` = list(Q1 = c(`Desirable effects` = "Large",
                                                     `Undesirable effects` = "Small",
                                                     `Overall certainty` = "Moderate",
                                                      Balance = "Favours intervention"),
                                              Q2 = c(`Desirable effects` = "Trivial",
                                                     `Undesirable effects` = "Small",
                                                     `Overall certainty` = "Moderate",
                                                     Balance = "Favours intervention")),
                Recommendation = c(Q1 = "One dose of 9vHPV vaccine is recommended for routine immunisation in immunocompetent males and females aged 9 to 26 years. The optimal age for HPV vaccination is around 12 to 13 years prior to HPV exposure",
                                   Q2 = "One dose of 9vHPV vaccine is recommended for routine immunisation in immunocompetent males and females aged 9 to 26 years. The optimal age for HPV vaccination is around 12 to 13 years prior to HPV exposure"))
