dat_influenza <- list(Initiation = "Not provided",
                      Question = c(Q1 = "Should adults over 65 years receive high-dose influenza vaccine (Fluzone) compared to standard-dose influenza vaccine?",
                                   Q2 = "Should adults over 65 years receive adjuvanted influenza vaccine (Fluad Quad) compared to standard-dose influenza vaccine?",
                                   Q3 = "Should adults over 65 years receive high-dose influenza vaccine (Fluzone) compared to adjuvanted influenza vaccine (Fluad Quad)?",
                                   Q4 = "Should children aged 2-17 years receive MDCK cell-derived influenza vaccine (Flucelvax Quad) compared to egg-based influenza vaccine?",
                                   Q5 = "Should adults over 18 years receive MDCK cell-derived influenza vaccine (Flucelvax Quad) compared to egg-based influenza vaccine?"),
                      Population = c(Q1 = "Adults over 65 years",
                                     Q2 = "Adults over 65 years",
                                     Q3 = "Adults over 65 years",
                                     Q4 = "Children aged 2-17 years",
                                     Q5 = "Adults over 18 years"),
                      Intervention = c(Q1 = "High-dose influenza vaccine (Fluzone)",
                                       Q2 = "Adjuvanted influenza vaccine (Fluad Quad)",
                                       Q3 = "High-dose influenza vaccine (Fluzone)",
                                       Q4 = "MDCK cell-derived influenza vaccine (Flucelvax Quad)",
                                       Q5 = "MDCK cell-derived influenza vaccine (Flucelvax Quad)"),
                      Comparator = c(Q1 = "Standard-dose influenza vaccine",
                                     Q2 = "Standard-dose influenza vaccine",
                                     Q3 = "Adjuvanted influenza vaccine (Fluad Quad)",
                                     Q4 = "Egg-based influenza vaccine",
                                     Q5 = "Egg-based influenza vaccine"),
                      Literature = c(Q1 = "37 studies including RCTs and observational",
                                     Q2 = "22 studies including RCTs and observational",
                                     Q3 = "2 RCTs and 10 observational studies",
                                     Q4 = "3 RCTs and 7 observational studies",
                                     Q5 = "2 RCTs and 13 observational studies"),
                      Outcomes = list(Q1 = list(`Post-influenza mortality up to 30 days` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Potential confounding"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Very serious", Reason = "Measurement limitations"),
                                                       Imprecision = c(Rating = "Serious", Reason = "Wide confidence intervals"),
                                                       Other = "None",
                                                       Certainty = "Very low",
                                                       Direction = "Little to no difference",
                                                       Importance = "Critical"),
                                                `Influenza- or pneumonia-associated mortality` =
                                                  list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Serious", Reason = "May include unrelated deaths"),
                                                       Imprecision = c(Rating = "Serious", Reason = "Wide confidence intervals"),
                                                       Other = "None",
                                                       Certainty = "Low",
                                                       Direction = "Moderate benefit",
                                                       Importance = "Critical"),
                                                `Influenza/pneumonia/respiratory-related hospitalisation up to 6 months` =
                                                  list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Serious", Reason = "ICD codes included pulmonary and influenza-like conditions and no laboratory confirmation"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "Moderate",
                                                       Direction = "Moderate benefit",
                                                       Importance = "Critical"),
                                                `Influenza/pneumonia/respiratory-related hospitalisation up to 1 year` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Only abstracts provided for two studies"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Serious", Reason = "ICD codes included pulmonary and influenza-like conditions and no laboratory confirmation"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "Low",
                                                       Direction = "Moderate benefit",
                                                       Importance = "Critical"),
                                                `Influenza/pneumonia/respiratory-related hospitalisation or ED visit` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Only abstracts provided for two studies"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Serious", Reason = "ICD codes included pulmonary and influenza-like conditions and no laboratory confirmation"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "Low",
                                                       Direction = "Moderate benefit",
                                                       Importance = "Critical"),
                                                `Serious adverse events or adverse events of special interest up to 6 months` =
                                                  list(`Risk of Bias` = c(Rating = "Very serious", Reason = "Small sample sizes"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "Moderate",
                                                       Direction = "Little to no difference",
                                                       Importance = "Critical"),
                                                `Influenza- or pneumonia-related office visits` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Rated moderate"),
                                                       Inconsistency = c(Rating = "Serious", Reason = "Variability between studies"),
                                                       Indirectness = c(Rating = "Serious", Reason = "No laboratory confirmation"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "Very low",
                                                       Direction = "Small benefit",
                                                       Importance = "Important"),
                                                `Laboratory-confirmed influenza` =
                                                  list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Serious", Reason = "Wide confidence intervals"),
                                                       Other = "None",
                                                       Certainty = "Moderate",
                                                       Direction = "Small benefit",
                                                       Importance = "Important"),
                                                `Cardiovascular events up to 8 months` =
                                                  list(`Risk of Bias` = c(Rating = "Extremely serious", Reason = "Unclear event definition"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "Very low",
                                                       Direction = "Little to no difference",
                                                       Importance = "Important"),
                                                `Systemic adverse events up to 28 days` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Rated moderate"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "Moderate",
                                                       Direction = "Little to no difference",
                                                       Importance = "Important"),
                                                `Local adverse events up to 28 days` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Rated moderate"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "Moderate",
                                                       Direction = "Moderate cost",
                                                       Importance = "Important"),
                                                `All-cause mortality up to 6 months` =
                                                  list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "High",
                                                       Direction = "Little to no difference",
                                                       Importance = "Important"),
                                                `All-cause hospitalisation` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Rated moderate"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "Moderate",
                                                       Direction = "Small benefit",
                                                       Importance = "Important")),
                                      Q2 = list(`Influenza- or pneumonia-related hospitalisation up to 17 weeks` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Potential confounding"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Serious", Reason = "No laboratory confirmation"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "Low",
                                                       Direction = "Small benefit",
                                                       Importance = "Critical"),
                                                `Influenza-related hospital encounters up to 14 days` =
                                                  list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Serious", Reason = "No laboratory confirmation"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "Moderate",
                                                       Direction = "Small benefit",
                                                       Importance = "Critical"),
                                                `Laboratory-confirmed influenza up to 4 months` =
                                                  list(`Risk of Bias` = c(Rating = "Very serious", Reason = "Potential confounding"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Serious", Reason = "Wide confidence intervals"),
                                                       Other = "None",
                                                       Certainty = "Very low",
                                                       Direction = "Moderate benefit",
                                                       Importance = "Important"),
                                                `Influenza-related office visits up to 14 days` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Potential confounding"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Serious", Reason = "No laboratory confirmation"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "Low",
                                                       Direction = "Small cost",
                                                       Importance = "Important"),
                                                `Influenza-like illness up to 1 year` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Potential confounding"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Serious", Reason = "No laboratory confirmation"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "Low",
                                                       Direction = "Little to no difference",
                                                       Importance = "Important"),
                                                `Hospitalisation for pneumonia, stroke and myocardial infarction up to 28 days` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Potential confounding"),
                                                       Inconsistency = c(Rating = "Serious", Reason = "Variability between studies"),
                                                       Indirectness = c(Rating = "Serious", Reason = "No laboratory confirmation"),
                                                       Imprecision = c(Rating = "Serious", Reason = "Wide confidence intervals"),
                                                       Other = "Strong association",
                                                       Certainty = "Very low",
                                                       Direction = "Small benefit",
                                                       Importance = "Important"),
                                                `Local adverse events up to 6 months` =
                                                  list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "High",
                                                       Direction = "Small cost",
                                                       Importance = "Important"),
                                                `Systemic adverse events up to 6 months` =
                                                  list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "High",
                                                       Direction = "Little to no difference",
                                                       Importance = "Important"),
                                                `Serious adverse events up to 1 year` =
                                                  list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "High",
                                                       Direction = "Little to no difference",
                                                       Importance = "Important"),
                                                `Adverse events of special interest` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Potential confounding"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "Very low",
                                                       Direction = "Little to no difference",
                                                       Importance = "Important")),
                                      Q3 = list(`Influenza-related hospitalisation up to 2 weeks` =
                                                  list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Serious", Reason = "No laboratory confirmation"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "Moderate",
                                                       Direction = "Little to no difference",
                                                       Importance = "Critical"),
                                                `Respiratory-related hospitalisation` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Potential confounding and missing data"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Serious", Reason = "No laboratory confirmation"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "Low",
                                                       Direction = "Small benefit",
                                                       Importance = "Important"),
                                                `Influenza-related office visits up to 14 days` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Potential confounding and missing data"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Serious", Reason = "No laboratory confirmation"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "Low",
                                                       Direction = "Small benefit",
                                                       Importance = "Important"),
                                                `Local adverse events up to 14 days` =
                                                  list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "High",
                                                       Direction = "Little to no difference",
                                                       Importance = "Important"),
                                                `Systemic adverse events up to 14 days` =
                                                  list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "High",
                                                       Direction = "Little to no difference",
                                                       Importance = "Important"),
                                                `Adverse events of special interest up to 84 days` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Potential confounding"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Serious", Reason = "Indirect comparison via meta-analysis"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "Low",
                                                       Direction = "Small benefit",
                                                       Importance = "Important")),
                                      Q4 = list(`Laboratory-confirmed influenza hospitalisation up to 6 months` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Potential confounding"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Serious", Reason = "Different age group"),
                                                       Imprecision = c(Rating = "Very serious", Reason = "Wide confidence intervals"),
                                                       Other = "None",
                                                       Certainty = "Very low",
                                                       Direction = "Moderate benefit",
                                                       Importance = "Critical"),
                                                `Influenza-related hospitalisation up to 6 months` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Potential confounding"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Very serious", Reason = "Wide confidence intervals"),
                                                       Other = "None",
                                                       Certainty = "Very low",
                                                       Direction = "Small benefit",
                                                       Importance = "Critical"),
                                                `Pneumonia-related hospitalisation up to 6 months` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Potential confounding"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Serious", Reason = "Wide confidence intervals"),
                                                       Other = "None",
                                                       Certainty = "Low",
                                                       Direction = "Moderate benefit",
                                                       Importance = "Critical"),
                                                `Serious adverse events up to 1 year` =
                                                  list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "High",
                                                       Direction = "Little to no difference",
                                                       Importance = "Critical"),
                                                `Influenza like illness up to 6 months` =
                                                  list(`Risk of Bias` = c(Rating = "Very serious", Reason = "Potential confounding"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Serious", Reason = "Wide confidence intervals"),
                                                       Other = "None",
                                                       Certainty = "Very low",
                                                       Direction = "Small benefit",
                                                       Importance = "Important"),
                                                `RT-PCR or culture confirmed influenza up to 6 months` =
                                                  list(`Risk of Bias` = c(Rating = "Very serious", Reason = "Potential confounding"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Serious", Reason = "Wide confidence intervals"),
                                                       Other = "None",
                                                       Certainty = "Very low",
                                                       Direction = "Little to no difference",
                                                       Importance = "Important"),
                                                `PCR-confirmed influenza A up to 6 months` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Potential confounding"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Very serious", Reason = "Wide confidence intervals"),
                                                       Other = "None",
                                                       Certainty = "Very low",
                                                       Direction = "Moderate benefit",
                                                       Importance = "Important"),
                                                `PCR-confirmed influenza B up to 6 months` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Potential confounding"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "Moderate",
                                                       Direction = "Moderate benefit",
                                                       Importance = "Important"),
                                                `All-cause hospitalisation up to 6 months` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Potential confounding"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Very serious", Reason = "Wide confidence intervals"),
                                                       Other = "None",
                                                       Certainty = "Very low",
                                                       Direction = "Small benefit",
                                                       Importance = "Important"),
                                                `Local adverse events up to 7 days` =
                                                  list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "High",
                                                       Direction = "Moderate cost",
                                                       Importance = "Important"),
                                                `Systemic adverse events up to 7 days` =
                                                  list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "High",
                                                       Direction = "Little to no difference",
                                                       Importance = "Important")),
                                      Q5 = list(`Laboratory-confirmed influenza hospitalisation up to 6 months` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Potential confounding"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Very serious", Reason = "Wide confidence intervals"),
                                                       Other = "None",
                                                       Certainty = "Very low",
                                                       Direction = "Small benefit",
                                                       Importance = "Critical"),
                                                `Influenza-related hospitalisation up to 6 months` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Potential confounding"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Serious", Reason = "Wide confidence intervals"),
                                                       Other = "None",
                                                       Certainty = "Low",
                                                       Direction = "Small benefit",
                                                       Importance = "Critical"),
                                                `Pneumonia-related hospitalisation up to 6 months` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Potential confounding"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Serious", Reason = "Non statistically significant results"),
                                                       Other = "None",
                                                       Certainty = "Low",
                                                       Direction = "Little to no difference",
                                                       Importance = "Critical"),
                                                `Serious adverse events up to 6 months` =
                                                  list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "High",
                                                       Direction = "Little to no difference",
                                                       Importance = "Critical"),
                                                `Influenza like illness up to 6 months` =
                                                  list(`Risk of Bias` = c(Rating = "Very serious", Reason = "Potential confounding"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Serious", Reason = "Wide confidence intervals"),
                                                       Other = "None",
                                                       Certainty = "Very low",
                                                       Direction = "Small benefit",
                                                       Importance = "Important"),
                                                `RT-PCR or culture confirmed influenza up to 6 months` =
                                                  list(`Risk of Bias` = c(Rating = "Very serious", Reason = "Potential confounding"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "Low",
                                                       Direction = "Little to no difference",
                                                       Importance = "Important"),
                                                `PCR-confirmed influenza A up to 6 months` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Potential confounding"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Very serious", Reason = "Wide confidence intervals"),
                                                       Other = "None",
                                                       Certainty = "Very low",
                                                       Direction = "Little to no difference",
                                                       Importance = "Important"),
                                                `PCR-confirmed influenza B up to 6 months` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Potential confounding"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Very serious", Reason = "Wide confidence intervals"),
                                                       Other = "None",
                                                       Certainty = "Very low",
                                                       Direction = "Moderate benefit",
                                                       Importance = "Important"),
                                                `All-cause hospitalisation up to 6 months` =
                                                  list(`Risk of Bias` = c(Rating = "Serious", Reason = "Potential confounding"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "Moderate",
                                                       Direction = "Moderate benefit",
                                                       Importance = "Important"),
                                                `Local adverse events up to 7 days` =
                                                  list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "High",
                                                       Direction = "Moderate cost",
                                                       Importance = "Important"),
                                                `Systemic adverse events up to 7 days` =
                                                  list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                       Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                       Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                       Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                       Other = "None",
                                                       Certainty = "High",
                                                       Direction = "Little to no difference",
                                                       Importance = "Important"))),
                      `Evidence to decision` = list(Q1 = c(`Desirable effects` = "Small",
                                                           `Undesirable effects` = "Small",
                                                           `Overall certainty` = "Moderate",
                                                            Balance = "Probably favours intervention"),
                                                    Q2 = c(`Desirable effects` = "Small",
                                                           `Undesirable effects` = "Small",
                                                           `Overall certainty` = "Low",
                                                           Balance = "Probably favours intervention"),
                                                    Q3 = c(`Desirable effects` = "Trivial",
                                                           `Undesirable effects` = "Trivial",
                                                           `Overall certainty` = "Low",
                                                           Balance = "Does not favour either intervention or comparison"),
                                                    Q4 = c(`Desirable effects` = "Varies",
                                                           `Undesirable effects` = "Trivial",
                                                           `Overall certainty` = "Very low",
                                                           Balance = "Does not favour either intervention or comparison"),
                                                    Q5 = c(`Desirable effects` = "Varies",
                                                           `Undesirable effects` = "Trivial",
                                                           `Overall certainty` = "Low",
                                                           Balance = "Does not favour either intervention or comparison")),
                Recommendation = c(Q1 = "High-dose influenza vaccine is recommended in preference to standard dose influenza vaccine in adults aged over 65 years",
                                   Q2 = "Adjuvanted influenza vaccine is recommended in preference to standard dose influenza vaccine in adults aged over 65 years",
                                   Q3 = "Neither adjuvanted influenza vaccine nor high-dose influenza vaccine is recommended in preference to the others in adults aged over 65 years",
                                   Q4 = "There is no preferential recommendation between the use of cell-derived influenza vaccine and standard dose egg-based influenza vaccine in children aged 2-17 years",
                                   Q5 = "There is no preferential recommendation between the use of cell-derived influenza vaccine and standard dose egg-based influenza vaccine in adults aged over 18 years"))
