dat_DTP <- list(Initiation = "Following PBAC recommendation of Vaxelis",
                Question = c(Q1 = "Should infants aged 6 weeks to 10 years use Vaxelis for primary vaccination in the same way as Infanrix hexa?"),
                Population = c(Q1 = "Infants from 6 weeks to 10 years"),
                Intervention = c(Q1 = "Vaxelis"),
                Comparator = c(Q1 = "Infanrix Hexa"),
                Literature = c(Q1 = "Five RCTs and two observational"),
                Outcomes = list(Q1 = list(`Immunogenicity at 5 months` =
                                            list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                 Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                 Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "None",
                                                 Certainty = "High",
                                                 Direction = "Little to no difference",
                                                 Importance = "Critical"),
                                          `Immunogenicity at 13 months with one dose of MenC/Hib(PRP-TT)` =
                                            list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                 Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                 Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                 Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                 Other = "None",
                                                 Certainty = "Moderate",
                                                 Direction = "Little to no difference",
                                                 Importance = "Critical"),
                                          `Immunogenicity at 13 months with one dose of booster` =
                                            list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                 Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                 Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "None",
                                                 Certainty = "High",
                                                 Direction = "Little to no difference",
                                                 Importance = "Critical"),
                                          `Immunogenicity at 13 months with one dose of booster after 2 dose primary` =
                                            list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                 Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                 Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "None",
                                                 Certainty = "High",
                                                 Direction = "Little to no difference",
                                                 Importance = "Critical"),
                                          `Serious adverse events up to 13 months` =
                                            list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                 Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                 Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "None",
                                                 Certainty = "High",
                                                 Direction = "Little to no difference",
                                                 Importance = "Critical"),
                                          `Solicited systemic adverse events up to 15 days` =
                                            list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                 Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                 Indirectness = c(Rating = "Serious", Reason = "Data pooled"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "None",
                                                 Certainty = "Moderate",
                                                 Direction = "Little to no difference",
                                                 Importance = "Important"),
                                          `Solicited local adverse events up to 15 days` =
                                            list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                 Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                 Indirectness = c(Rating = "Serious", Reason = "Data pooled"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "None",
                                                 Certainty = "Moderate",
                                                 Direction = "Little to no difference",
                                                 Importance = "Important"),
                                          `Solicited fever events up to 15 days` =
                                            list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                 Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                 Indirectness = c(Rating = "Serious", Reason = "Data pooled"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "None",
                                                 Certainty = "Moderate",
                                                 Direction = "Little to no difference",
                                                 Importance = "Important"),
                                          `Adverse events of special interest up to 15 days` =
                                            list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                 Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                 Indirectness = c(Rating = "Serious", Reason = "Data pooled"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "None",
                                                 Certainty = "Moderate",
                                                 Direction = "Little to no difference",
                                                 Importance = "Important"))),
                `Evidence to decision` = list(Q1 = c(`Desirable effects` = "Trivial",
                                                     `Undesirable effects` = "Trivial",
                                                     `Overall certainty` = "High",
                                                     Balance = "Does not favour either intervention or comparison")),
                Recommendation = c(Q1 = "There is no preferential recommendation between the use of DT5aP-HBV-IPV-Hib(PRP-OMP) vaccine (Vaxelis) and DT3aP-HBV-IPV-Hib(PRP-TT) vaccine (Infanrix hexa) for primary vaccination in infants and children aged 6 months to 10 years"))
