dat_cholera <- list(Initiation = "Anticipation of TGA approval of Vaxchora",
                    Question = c(Q1 = "Should children and adults aged 2 years and over who have a high risk of exposure to cholera use Vaxchora cholera vaccine?"),
                    Population = c(Q1 = "Children and adults aged 2 years and over"),
                    Intervention = c(Q1 = "Vaxchora"),
                    Comparator = c(Q1 = "Placebo"),
                    Literature = c(Q1 = "Seven RCTs"),
                    Outcomes = list(Q1 = list(`Efficacy against severe cholera diarrhoea up to 10 days` =
                                                list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                     Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                     Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                     Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                     Other = "None",
                                                     Certainty = "Moderate",
                                                     Direction = "Large benefit",
                                                     Importance = "Critical"),
                                              `Efficacy against severe cholera diarrhoea up to 90 days` =
                                                list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                     Inconsistency = c(Rating = "Not assessed",Reason = "Only one study included"),
                                                     Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                     Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                     Other = "None",
                                                     Certainty = "Moderate",
                                                     Direction = "Large benefit",
                                                     Importance = "Critical"),
                                              `Efficacy against moderate or severe cholera diarrhoea up to 10 days` =
                                                list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                     Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                     Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                     Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                     Other = "None",
                                                     Certainty = "Moderate",
                                                     Direction = "Large benefit",
                                                     Importance = "Critical"),
                                           `Efficacy against moderate or severe cholera diarrhoea up to 90 days` =
                                             list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                  Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                  Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                  Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                  Other = "None",
                                                  Certainty = "Moderate",
                                                  Direction = "Large benefit",
                                                  Importance = "Critical"),
                                           `Efficacy against mild or worse severity cholera diarrhoea up to 10 days` =
                                             list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                  Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                  Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                  Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                  Other = "None",
                                                  Certainty = "High",
                                                  Direction = "Large benefit",
                                                  Importance = "Critical"),
                                           `Efficacy against mild or worse severity cholera diarrhoea up to 90 days` =
                                             list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                  Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                  Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                  Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                  Other = "None",
                                                  Certainty = "High",
                                                  Direction = "Large benefit",
                                                  Importance = "Critical"),
                                           `Serious adverse events up to 180 days` =
                                             list(`Risk of Bias` = c(Rating = "Serious", Reason = "Selective outcome reporting"),
                                                  Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                  Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                  Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                  Other = "None",
                                                  Certainty = "Moderate",
                                                  Direction = "Little to no difference",
                                                  Importance = "Critical"),
                                           `Serum vibriocidal antibody seroconversion rate up to 10 days` =
                                             list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                  Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                  Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                  Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                  Other = "None",
                                                  Certainty = "High",
                                                  Direction = "Large benefit",
                                                  Importance = "Important"),
                                           `Serum vibriocidal antibody seroconversion rate up to 180 days` =
                                             list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                  Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                  Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                  Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                  Other = "None",
                                                  Certainty = "Moderate",
                                                  Direction = "Large benefit",
                                                  Importance = "Important"),
                                           `Solicited systemic adverse events up to 7 days` =
                                             list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                  Inconsistency = c(Rating = "Serious", Reason = "Variability between studies"),
                                                  Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                  Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                  Other = "None",
                                                  Certainty = "Moderate",
                                                  Direction = "Little to no difference",
                                                  Importance = "Important"))),
                    `Evidence to decision` = list(Q1 = c(`Desirable effects` = "Moderate",
                                                         `Undesirable effects` = "Trivial",
                                                         `Overall certainty` = "Moderate",
                                                         Balance = "Favours intervention")),
                    Recommendation = c(Q1 = "Vaxchora cholera vaccine is recommended as an alternative to Dukoral cholera vaccine in immunocompetent children and adults aged at least two years old who have a high risk of exposure to cholera"))
