dat_rabies <- list(Initiation = "Following ACIP and TGA recommendations for a two dose Verorab schedule",
                   Question = c(Q1 = "Should people who are indicated to receive rabies pre-exposure prophylaxis vaccination receive 3 doses of Verorab?",
                                Q2 = "Should people who are indicated to receive rabies pre-exposure prophylaxis vaccination receive 2 doses of Verorab?",
                                Q3 = "Should people who are indicated to receive rabies pre-exposure prophylaxis vaccination receive 2 doses of HDCV or PCECV?"),
                   Population = c(Q1 = "People indicated to receive rabies pre-exposure prophylaxis vaccination",
                                  Q2 = "People indicated to receive rabies pre-exposure prophylaxis vaccination",
                                  Q3 = "People indicated to receive rabies pre-exposure prophylaxis vaccination"),
                   Intervention = c(Q1 = "3 doses Verorab",
                                    Q2 = "2 doses Verorab",
                                    Q3 = "2 doses HDCV or PCECV"),
                   Comparator = c(Q1 = "3 doses HDCV or PCECV",
                                  Q2 = "3 doses HDCV or PCECV",
                                  Q3 = "3 doses HDCV or PCECV"),
                   Literature = c(Q1 = "1 RCT and 3 observational studies",
                                  Q2 = "1 RCT and 1 observational study",
                                  Q3 = "4 RCTs and 3 observational studies"),
                   Outcomes = list(Q1 = list(`Vaccine-related serious adverse events up to 1 month` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                    Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                    Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                    Other = "None",
                                                    Certainty = "Moderate",
                                                    Direction = "Little to no difference",
                                                    Importance = "Critical"),
                                             `RVNA seroconversion rate up to 28 days` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                    Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                    Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                    Other = "None",
                                                    Certainty = "High",
                                                    Direction = "Little to no difference",
                                                    Importance = "Important"),
                                             `RVNA seroconversion rate up to 1 year` =
                                               list(`Risk of Bias` = c(Rating = "Serious", Reason = "Potential confounding and missing data"),
                                                    Inconsistency = c(Rating = "Serious", Reason = "Variability between studies"),
                                                    Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                    Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                    Other = "None",
                                                    Certainty = "Very low",
                                                    Direction = "Little to no difference",
                                                    Importance = "Important"),
                                             `Local adverse events up to 1 month` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                    Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                    Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                    Other = "None",
                                                    Certainty = "Moderate",
                                                    Direction = "Little to no difference",
                                                    Importance = "Important"),
                                             `Systemic adverse events up to 1 month` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                    Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                    Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                    Other = "None",
                                                    Certainty = "Moderate",
                                                    Direction = "Little to no difference",
                                                    Importance = "Important")),
                                   Q2 = list(`Vaccine-related serious adverse events up to 180 days` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                    Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                    Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                    Other = "None",
                                                    Certainty = "Moderate",
                                                    Direction = "Little to no difference",
                                                    Importance = "Critical"),
                                             `RVNA seroconversion rate up to 14 days` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                    Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                    Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                    Other = "None",
                                                    Certainty = "Moderate",
                                                    Direction = "Little to no difference",
                                                    Importance = "Important"),
                                             `RVNA seroconversion rate up to 180 days` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                    Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                    Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                    Other = "None",
                                                    Certainty = "Moderate",
                                                    Direction = "Little to no difference",
                                                    Importance = "Important"),
                                             `RVNA seroconversion rate up to 1 year` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                    Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                    Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                    Other = "None",
                                                    Certainty = "Moderate",
                                                    Direction = "Little to no difference",
                                                    Importance = "Important"),
                                             `Local adverse events up to 7 days` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                    Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                    Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                    Other = "None",
                                                    Certainty = "Moderate",
                                                    Direction = "Small benefit",
                                                    Importance = "Important"),
                                             `Systemic adverse events up to 7 days` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                    Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                    Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                    Other = "None",
                                                    Certainty = "Moderate",
                                                    Direction = "Little to no difference",
                                                    Importance = "Important")),
                                   Q3 = list(`Vaccine-related serious adverse events up to 1 year` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                    Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                    Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                    Other = "None",
                                                    Certainty = "Moderate",
                                                    Direction = "Little to no difference",
                                                    Importance = "Critical"),
                                             `RVNA seroconversion rate up to 7 days` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                    Indirectness = c(Rating = "Serious", Reason = "Different schedule interval"),
                                                    Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                    Other = "None",
                                                    Certainty = "Low",
                                                    Direction = "Little to no difference",
                                                    Importance = "Important"),
                                             `RVNA seroconversion rate up to 180 days` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                    Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                    Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                    Other = "None",
                                                    Certainty = "Moderate",
                                                    Direction = "Small cost",
                                                    Importance = "Important"),
                                             `RVNA seroconversion rate up to 1 year` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Very serious", Reason = "Variability between studies"),
                                                    Indirectness = c(Rating = "Serious", Reason = "Different schedule interval"),
                                                    Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                    Other = "None",
                                                    Certainty = "Very low",
                                                    Direction = "Little to no difference",
                                                    Importance = "Important"),
                                             `Local adverse events up to 7 days` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                    Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                    Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                    Other = "None",
                                                    Certainty = "Moderate",
                                                    Direction = "Small benefit",
                                                    Importance = "Important"),
                                             `Systemic adverse events up to 7 days` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                    Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                    Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                    Other = "None",
                                                    Certainty = "Moderate",
                                                    Direction = "Small benefit",
                                                    Importance = "Important"))),
                   `Evidence to decision` = list(Q1 = c(`Desirable effects` = "Trivial",
                                                        `Undesirable effects` = "Trivial",
                                                        `Overall certainty` = "Moderate",
                                                        Balance = "Does not favour either comparison or intervention"),
                                                 Q2 = c(`Desirable effects` = "Small",
                                                        `Undesirable effects` = "Small",
                                                        `Overall certainty` = "Moderate",
                                                        Balance = "Does not favour either comparison or intervention"),
                                                 Q3 = c(`Desirable effects` = "Small",
                                                        `Undesirable effects` = "Small",
                                                        `Overall certainty` = "Low",
                                                        Balance = "Does not favour either comparison or intervention")),
                   Recommendation = c(Q1 = "A 2-dose pre-exposure prophylaxis Verorab rabies vaccine schedule is recommended as an alternative to currently approved HDCV/PCECV rabies vaccines in people indicated to receive pre-exposure prophylaxis rabies vaccination",
                                      Q2 = "A 2-dose pre-exposure prophylaxis Verorab rabies vaccine schedule is recommended as an alternative to currently approved HDCV/PCECV rabies vaccines in people indicated to receive pre-exposure prophylaxis rabies vaccination",
                                      Q3 = "A 2-dose pre-exposure prophylaxis Verorab rabies vaccine schedule is recommended as an alternative to currently approved HDCV/PCECV rabies vaccines in people indicated to receive pre-exposure prophylaxis rabies vaccination"))
