dat_pneumococcal <- list(Initiation = "Following TGA recommendation of 15vPCV and 20vPCV",
                         Question = c(Q1 = "What should the recommendation be for the use of 15vPCV for non-Indigenous adults aged over 70 years without underlying risk conditions who are currently recommended 13vPCV?",
                                      Q2 = "What should the recommendation be for the use of 20vPCV for non-Indigenous adults aged over 70 years without underlying risk conditions who are currently recommended 13vPCV?",
                                      Q3 = "What should the recommendation be for the use of 15vPCV+23vPPV for Indigenous adults aged over 50 years without underlying risk conditions who are currently recommended 13vPCV+23vPPV?",
                                      Q4 = "What should the recommendation be for the use of 20vPCV+23vPPV for Indigenous adults aged over 50 years without underlying risk conditions who are currently recommended 13vPCV+23vPPV?",
                                      Q5 = "What should the recommendation be for the use of 15vPCV+23vPPV for adults aged over 18 years with underlying risk conditions who are currently recommended 13vPCV+23vPPV?",
                                      Q6 = "What should the recommendation be for the use of 20vPCV+23vPPV for adults aged over 18 years with underlying risk conditions who are currently recommended 13vPCV+23vPPV?"),
                         Population = c(Q1 = "Non-Indigenous adults aged over 70 years without underlying risk conditions",
                                        Q2 = "Non-Indigenous adults aged over 70 years without underlying risk conditions",
                                        Q3 = "Indigenous adults aged over 50 years without underlying risk conditions",
                                        Q4 = "Indigenous adults aged over 50 years without underlying risk conditions",
                                        Q5 = "Adults aged over 18 years with underlying risk conditions",
                                        Q6 = "Adults aged over 18 years with underlying risk conditions"),
                         Intervention = c(Q1 = "15vPCV",
                                          Q2 = "20vPCV",
                                          Q3 = "15vPCV+23vPPV",
                                          Q4 = "20vPCV+23vPPV",
                                          Q5 = "15vPCV+23vPPV",
                                          Q6 = "20vPCV+23vPPV"),
                         Comparator = c(Q1 = "13vPCV",
                                        Q2 = "13vPCV",
                                        Q3 = "13vPCV+23vPPV",
                                        Q4 = "13vPCV+23vPPV",
                                        Q5 = "13vPCV+23vPPV",
                                        Q6 = "13vPCV+23vPPV"),
                         Literature = c(Q1 = "6 RCTs",
                                        Q2 = "4 RCTs",
                                        Q3 = "3 RCTs",
                                        Q5 = "4 RCTs",
                                        Q5 = "2 RCTs",
                                        Q6 = "4 RCTs"),
                         Outcomes = list(Q1 = list(`Serious adverse events` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                          Imprecision = c(Rating = "Serious", Reason = "Low number of events"),
                                                          Other = "None",
                                                          Certainty = "Moderate",
                                                          Direction = "Little to no difference",
                                                          Importance = "Critical"),
                                                   `OPA GMT ratios up to 30 days` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                          Imprecision = c(Rating = "Serious", Reason = "Underpowered"),
                                                          Other = "None",
                                                          Certainty = "Moderate",
                                                          Direction = "Moderate benefit",
                                                          Importance = "Important"),
                                                   `OPA GMT ratios up to 12 months` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                          Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                          Imprecision = c(Rating = "Serious", Reason = "Underpowered"),
                                                          Other = "None",
                                                          Certainty = "Moderate",
                                                          Direction = "Moderate benefit",
                                                          Importance = "Important"),
                                                   `GMT rise up to 30 days` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "High",
                                                          Direction = "Moderate benefit",
                                                          Importance = "Important"),
                                                   `IgG GMC ratios up to 30 days` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                          Imprecision = c(Rating = "Serious", Reason = "Underpowered"),
                                                          Other = "None",
                                                          Certainty = "Moderate",
                                                          Direction = "Moderate benefit",
                                                          Importance = "Important"),
                                                   `GMC rise up to 30 days` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "High",
                                                          Direction = "Moderate benefit",
                                                          Importance = "Important"),
                                                   `Local adverse events` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "High",
                                                          Direction = "Small cost",
                                                          Importance = "Important"),
                                                   `Systemic adverse events` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "High",
                                                          Direction = "Small cost",
                                                          Importance = "Important")),
                                         Q2 = list(`Serious adverse events` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "High",
                                                          Direction = "Little to no difference",
                                                          Importance = "Critical"),
                                                   `OPA GMT ratios up to 1 month` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Serious", Reason = "Different age group"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "Moderate",
                                                          Direction = "Little to no difference",
                                                          Importance = "Important"),
                                                   `GMT rise up to 1 month` =
                                                     list(`Risk of Bias` = c(Rating = "Serious", Reason = "Reporting bias"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "Moderate",
                                                          Direction = "Moderate benefit",
                                                          Importance = "Important"),
                                                   `GMC rise up to 1 month` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                          Indirectness = c(Rating = "Very serious", Reason = "Different age group and ethnicity"),
                                                          Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                          Other = "None",
                                                          Certainty = "Very low",
                                                          Direction = "Little to no difference",
                                                          Importance = "Important"),
                                                   `Local adverse events` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "High",
                                                          Direction = "Small cost",
                                                          Importance = "Important"),
                                                   `Systemic adverse events` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "High",
                                                          Direction = "Small cost",
                                                          Importance = "Important"),
                                                   `OPA GMFR up to 1 month` =
                                                     list(`Risk of Bias` = c(Rating = "Serious", Reason = "Reporting bias"),
                                                          Inconsistency = c(Rating = "Serious", Reason = "Variability between studies"),
                                                          Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "Low",
                                                          Direction = "Moderate benefit",
                                                          Importance = "Important")),
                                         Q3 = list(`Serious adverse events` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Serious", Reason = "Different ethnicity and schedule interval"),
                                                          Imprecision = c(Rating = "Serious", Reason = "Low number of events"),
                                                          Other = "None",
                                                          Certainty = "Low",
                                                          Direction = "Little to no difference",
                                                          Importance = "Critical"),
                                                   `OPA GMT ratios up to 30 days` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Serious", Reason = "Different ethnicity and schedule interval"),
                                                          Imprecision = c(Rating = "Serious", Reason = "Underpowered"),
                                                          Other = "None",
                                                          Certainty = "Low",
                                                          Direction = "Little to no difference",
                                                          Importance = "Important"),
                                                   `GMT rise up to 30 days` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Serious", Reason = "Different ethnicity and schedule interval"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "Moderate",
                                                          Direction = "Little to no difference",
                                                          Importance = "Important"),
                                                   `IgG GMC ratios up to 30 days` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Serious", Reason = "Different ethnicity and schedule interval"),
                                                          Imprecision = c(Rating = "Serious", Reason = "Underpowered"),
                                                          Other = "None",
                                                          Certainty = "Low",
                                                          Direction = "Little to no difference",
                                                          Importance = "Important"),
                                                   `GMC rise up to 30 days` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Serious", Reason = "Different ethnicity and schedule interval"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "Moderate",
                                                          Direction = "Little to no difference",
                                                          Importance = "Important"),
                                                   `Local adverse events` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Serious", Reason = "Different ethnicity and schedule interval"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "Moderate",
                                                          Direction = "Little to no difference",
                                                          Importance = "Important"),
                                                   `Systemic adverse events` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Serious", Reason = "Different ethnicity and schedule interval"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "Moderate",
                                                          Direction = "Little to no difference",
                                                          Importance = "Important")),
                                         Q4 = list(`Serious adverse events` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Very serious", Reason = "Different interventions and comparators"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "Low",
                                                          Direction = "Little to no difference",
                                                          Importance = "Critical"),
                                                   `OPA GMT ratios up to 1 month` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                          Indirectness = c(Rating = "Very serious", Reason = "Different interventions and ethnicity"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "Low",
                                                          Direction = "Small benefit",
                                                          Importance = "Important"),
                                                   `GMT rise up to 1 month` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Very serious", Reason = "Different interventions and ethnicity"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "Low",
                                                          Direction = "Moderate benefit",
                                                          Importance = "Important"),
                                                   `Local adverse events up to 7 days` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Very serious", Reason = "Different interventions and comparators"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "Low",
                                                          Direction = "Small cost",
                                                          Importance = "Important"),
                                                   `Systemic adverse events` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Very serious", Reason = "Different interventions and comparators"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "Low",
                                                          Direction = "Small cost",
                                                          Importance = "Important"),
                                                   `IgG GMFR up to 1 month` =
                                                     list(`Risk of Bias` = c(Rating = "Serious", Reason = "Reporting bias"),
                                                          Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                          Indirectness = c(Rating = "Very serious", Reason = "Different interventions and ethnicity"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "Very low",
                                                          Direction = "Little to no difference",
                                                          Importance = "Important")),
                                         Q5 = list(`Serious adverse events` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Serious", Reason = "Different population and schedule interval"),
                                                          Imprecision = c(Rating = "Serious", Reason = "Low number of events"),
                                                          Other = "None",
                                                          Certainty = "Low",
                                                          Direction = "Little to no difference",
                                                          Importance = "Critical"),
                                                   `OPA GMT ratios up to 30 days` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Serious", Reason = "Different population and schedule interval"),
                                                          Imprecision = c(Rating = "Serious", Reason = "Underpowered"),
                                                          Other = "None",
                                                          Certainty = "Low",
                                                          Direction = "Little to no difference",
                                                          Importance = "Important"),
                                                   `GMT rise up to 30 days` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Serious", Reason = "Different population and schedule interval"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "Moderate",
                                                          Direction = "Little to no difference",
                                                          Importance = "Important"),
                                                   `IgG GMC ratios up to 30 days` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Serious", Reason = "Different population and schedule interval"),
                                                          Imprecision = c(Rating = "Serious", Reason = "Underpowered"),
                                                          Other = "None",
                                                          Certainty = "Low",
                                                          Direction = "Little to no difference",
                                                          Importance = "Important"),
                                                   `GMC rise up to 30 days` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Serious", Reason = "Different population and schedule interval"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "Moderate",
                                                          Direction = "Little to no difference",
                                                          Importance = "Important"),
                                                   `Local adverse events` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Serious", Reason = "Different population and schedule interval"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "Moderate",
                                                          Direction = "Little to no difference",
                                                          Importance = "Important"),
                                                   `Systemic adverse events` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Serious", Reason = "Different population and schedule interval"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "Moderate",
                                                          Direction = "Little to no difference",
                                                          Importance = "Important")),
                                         Q6 = list(`Serious adverse events` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Very serious", Reason = "Different interventions and comparators"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "Low",
                                                          Direction = "Little to no difference",
                                                          Importance = "Critical"),
                                                   `OPA GMT ratios up to 1 month` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                          Indirectness = c(Rating = "Very serious", Reason = "Different interventions and ethnicity"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "Low",
                                                          Direction = "Small benefit",
                                                          Importance = "Important"),
                                                   `GMT rise up to 1 month` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Very serious", Reason = "Different interventions and ethnicity"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "Low",
                                                          Direction = "Moderate benefit",
                                                          Importance = "Important"),
                                                   `Local adverse events up to 7 days` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Very serious", Reason = "Different interventions and comparators"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "Low",
                                                          Direction = "Small cost",
                                                          Importance = "Important"),
                                                   `Systemic adverse events` =
                                                     list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                          Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                          Indirectness = c(Rating = "Very serious", Reason = "Different interventions and comparators"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "Low",
                                                          Direction = "Small cost",
                                                          Importance = "Important"),
                                                   `IgG GMFR up to 1 month` =
                                                     list(`Risk of Bias` = c(Rating = "Serious", Reason = "Reporting bias"),
                                                          Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                          Indirectness = c(Rating = "Very serious", Reason = "Different interventions and ethnicity"),
                                                          Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                          Other = "None",
                                                          Certainty = "Very low",
                                                          Direction = "Little to no difference",
                                                          Importance = "Important"))),
                         `Evidence to decision` = list(Q1 = c(`Desirable effects` = "Small",
                                                              `Undesirable effects` = "Small",
                                                              `Overall certainty` = "Moderate",
                                                               Balance = "Does not favour either comparison or intervention"),
                                                       Q2 = c(`Desirable effects` = "Varies",
                                                              `Undesirable effects` = "Small",
                                                              `Overall certainty` = "Low",
                                                              Balance = "Does not favour either comparison or intervention"),
                                                       Q3 = c(`Desirable effects` = "Varies",
                                                              `Undesirable effects` = "Small",
                                                              `Overall certainty` = "Low",
                                                              Balance = "Does not favour either comparison or intervention"),
                                                       Q4 = c(`Desirable effects` = "Small",
                                                              `Undesirable effects` = "Small",
                                                              `Overall certainty` = "Moderate",
                                                              Balance = "Does not favour either comparison or intervention"),
                                                       Q5 = c(`Desirable effects` = "Unknown",
                                                              `Undesirable effects` = "Small",
                                                              `Overall certainty` = "Low",
                                                              Balance = "Does not favour either comparison or intervention"),
                                                       Q6 = c(`Desirable effects` = "Unknown",
                                                              `Undesirable effects` = "Small",
                                                              `Overall certainty` = "Low",
                                                              Balance = "Does not favour either comparison or intervention")),
                         Recommendation = c(Q1 = "15vPCV vaccine is recommended as an alternative to 13vPCV vaccine in non-Indigenous adults aged over 70 years without special risk factors. It should be noted that 15vPCV provides additional anticipated protection against two more serotypes.",
                                            Q2 = "15vPCV+23vPPV vaccine is recommended as an alternative to 13vPCV+23vPPV vaccine in Indigenous adults aged over 50 years without special risk factors. It should be noted that 15vPCV provides additional anticipated protection against two more serotypes.",
                                            Q3 = "15vPCV+23vPPV vaccine is recommended as an alternative to 13vPCV+23vPPV vaccine in adults aged over 18 years with special risk factors. It should be noted that 15vPCV provides additional anticipated protection against two more serotypes.",
                                            Q4 = "20vPCV vaccine is recommended as an alternative to 13vPCV and 15vPCV vaccines in non-Indigenous adults aged over 70 years without special risk factors. It should be noted that 20vPCV provides additional anticipated protection against seven more serotypes compared to 13vPCV. There is no evidence that compares 15vPCV and 20vPCV.",
                                            Q5 = "20vPCV+23vPPV vaccine is recommended as an alternative to 13vPCV+23vPPV and 15vPCV+23vPPV vaccines in Indigenous adults aged over 50 years without special risk factors. It should be noted that 20vPCV provides additional anticipated protection against seven more serotypes compared to 13vPCV. The additional anticipated protection provided by 20vPCV+23vPPV compared to 13vPCV+23vPPV or 15vPCV+23vPPV is unknown.",
                                            Q6 = "20vPCV+23vPPV vaccine is recommended as an alternative to 13vPCV+23vPPV and 15vPCV+23vPPV vaccines in adults aged over 18 years with special risk factors. It should be noted that 20vPCV provides additional anticipated protection against seven more serotypes compared to 13vPCV. The additional anticipated protection provided by 20vPCV+23vPPV compared to 13vPCV+23vPPV or 15vPCV+23vPPV is unknown."))