dat_zoster <- list(Initiation = "Not provided",
                   Question = c(Q1 = "Should immunocompetent adults aged over 50 years receive Shingrix instead of placebo for protection against herpes zoster?",
                                Q2 = "Should immunocompetent adults aged over 50 years receive Shingrix instead of Zostavax for protection against herpes zoster?",
                                Q3 = "Should immunocompromised adults aged over 18 years receive Shingrix instead of placebo for protection against herpes zoster?"),
                   Population = c(Q1 = "Immunocompetent adults aged over 50 years",
                                  Q2 = "Immunocompetent adults aged over 50 years",
                                  Q3 = "Immunocompromised adults aged over 18 years"),
                   Intervention = c(Q1 = "2 doses Shingrix",
                                    Q2 = "2 doses Shingrix",
                                    Q3 = "2 doses Shingrix"),
                   Comparator = c(Q1 = "Placebo",
                                  Q2 = "1 dose of Zostavax",
                                  Q3 = "Placebo"),
                   Literature = c(Q1 = "2 RCTs and 1 observational study",
                                  Q2 = "7 RCTs and 1 observational study",
                                  Q3 = "5 RCTs and 3 observational studies"),
                   Outcomes = list(Q1 = list(`Efficacy against confirmed herpes zoster infection up to 3 years` =
                                            list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                 Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                 Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "Very strong association",
                                                 Certainty = "High",
                                                 Direction = "Large benefit",
                                                 Importance = "Critical"),
                                          `Efficacy against post-herpetic neuralgia up to 3 years` =
                                            list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                 Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                 Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "Strong association",
                                                 Certainty = "High",
                                                 Direction = "Large benefit",
                                                 Importance = "Critical"),
                                          `Herpes zoster-related hospitalisation up to 4 years` =
                                            list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                 Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                 Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                 Imprecision = c(Rating = "Very serious", Reason = "Wide confidence intervals"),
                                                 Other = "None",
                                                 Certainty = "Low",
                                                 Direction = "Moderate benefit",
                                                 Importance = "Critical"),
                                          `Serious adverse events up to 1 year` =
                                            list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                 Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                 Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "None",
                                                 Certainty = "High",
                                                 Direction = "Little to no difference",
                                                 Importance = "Critical"),
                                          `Local adverse events up to 7 days` =
                                            list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                 Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                 Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "Strong association",
                                                 Certainty = "High",
                                                 Direction = "Large cost",
                                                 Importance = "Important"),
                                          `Systemic adverse events up to 7 days` =
                                            list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                 Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                 Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "Strong association",
                                                 Certainty = "High",
                                                 Direction = "Large cost",
                                                 Importance = "Important"),
                                          `Unsolicited adverse events up to 30 days` =
                                            list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                 Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                 Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                 Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                 Other = "Strong association",
                                                 Certainty = "High",
                                                 Direction = "Moderate cost",
                                                 Importance = "Important")),
                                   Q2 = list(`Efficacy against confirmed herpes zoster infection up to 3 years` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                    Indirectness = c(Rating = "Serious", Reason = "Indirect comparison via meta-analysis"),
                                                    Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                    Other = "None",
                                                    Certainty = "Moderate",
                                                    Direction = "Large benefit",
                                                    Importance = "Critical"),
                                             `Efficacy against post-herpetic neuralgia up to 3 years` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                    Indirectness = c(Rating = "Serious", Reason = "Indirect comparison via meta-analysis"),
                                                    Imprecision = c(Rating = "Very serious", Reason = "Wide confidence intervals"),
                                                    Other = "None",
                                                    Certainty = "Very low",
                                                    Direction = "Moderate benefit",
                                                    Importance = "Critical"),
                                             `Serious adverse events up to 1 year` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Serious", Reason = "Wide prediction intervals"),
                                                    Indirectness = c(Rating = "Serious", Reason = "Indirect comparison via meta-analysis"),
                                                    Imprecision = c(Rating = "Serious", Reason = "Wide confidence intervals"),
                                                    Other = "None",
                                                    Certainty = "Very low",
                                                    Direction = "Little to no difference",
                                                    Importance = "Critical"),
                                             `Local adverse events up to 42 days` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Serious", Reason = "Wide prediction intervals"),
                                                    Indirectness = c(Rating = "Serious", Reason = "Indirect comparison via meta-analysis"),
                                                    Imprecision = c(Rating = "Serious", Reason = "Wide confidence intervals"),
                                                    Other = "None",
                                                    Certainty = "Very low",
                                                    Direction = "Moderate cost",
                                                    Importance = "Important"),
                                             `Systemic adverse events up to 42 days` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Serious", Reason = "Wide prediction intervals"),
                                                    Indirectness = c(Rating = "Serious", Reason = "Indirect comparison via meta-analysis"),
                                                    Imprecision = c(Rating = "Serious", Reason = "Wide confidence intervals"),
                                                    Other = "None",
                                                    Certainty = "Very low",
                                                    Direction = "Moderate cost",
                                                    Importance = "Important")),
                                   Q3 = list(`Efficacy against confirmed herpes zoster infection up to 1 year` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                    Indirectness = c(Rating = "Serious", Reason = "Restricted population"),
                                                    Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                    Other = "None",
                                                    Certainty = "Moderate",
                                                    Direction = "Large benefit",
                                                    Importance = "Critical"),
                                             `Herpes zoster infection up to 1 year` =
                                               list(`Risk of Bias` = c(Rating = "Serious", Reason = "Potential confounding"),
                                                    Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                    Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                    Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                    Other = "None",
                                                    Certainty = "Moderate",
                                                    Direction = "Large benefit",
                                                    Importance = "Critical"),
                                             `Efficacy against post-herpetic neuralgia up to 1 year` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                    Indirectness = c(Rating = "Serious", Reason = "Restricted population"),
                                                    Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                    Other = "None",
                                                    Certainty = "Moderate",
                                                    Direction = "Large benefit",
                                                    Importance = "Critical"),
                                             `Serious adverse events up to 1 year` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                    Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                    Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                    Other = "None",
                                                    Certainty = "High",
                                                    Direction = "Little to no difference",
                                                    Importance = "Critical"),
                                             `Herpes zoster-related hospitalisation up to 2 years` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                    Indirectness = c(Rating = "Serious", Reason = "Restricted population"),
                                                    Imprecision = c(Rating = "Serious", Reason = "Low number of events"),
                                                    Other = "None",
                                                    Certainty = "Moderate",
                                                    Direction = "Large benefit",
                                                    Importance = "Critical"),
                                             `Local adverse events up to 7 days` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                    Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                    Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                    Other = "None",
                                                    Certainty = "High",
                                                    Direction = "Large cost",
                                                    Importance = "Important"),
                                             `Systemic adverse events up to 7 days` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                    Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                    Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                    Other = "None",
                                                    Certainty = "High",
                                                    Direction = "Moderate cost",
                                                    Importance = "Important"),
                                             `Unsolicited adverse events up to 30 days` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                    Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                    Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                    Other = "None",
                                                    Certainty = "High",
                                                    Direction = "Little to no difference",
                                                    Importance = "Important"),
                                             `Potential immune-mediated disease up to 1 year` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                    Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                    Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                    Other = "None",
                                                    Certainty = "High",
                                                    Direction = "Little to no difference",
                                                    Importance = "Important"),
                                             `Humoral immunogenicity up to 1 month` =
                                               list(`Risk of Bias` = c(Rating = "Not serious", Reason = "None"),
                                                    Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                    Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                    Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                    Other = "None",
                                                    Certainty = "High",
                                                    Direction = "Large benefit",
                                                    Importance = "Important"),
                                             `Cell-mediated immunogenicity up to 1 month` =
                                               list(`Risk of Bias` = c(Rating = "Serious", Reason = "Non-randomised sample from randomised cohort"),
                                                    Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                    Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                    Imprecision = c(Rating = "Not serious", Reason = "None"),
                                                    Other = "None",
                                                    Certainty = "Moderate",
                                                    Direction = "Large benefit",
                                                    Importance = "Important"))),
                   `Evidence to decision` = list(Q1 = c(`Desirable effects` = "Large",
                                                        `Undesirable effects` = "Small",
                                                        `Overall certainty` = "High",
                                                        Balance = "Favours intervention"),
                                                 Q2 = c(`Desirable effects` = "Large",
                                                        `Undesirable effects` = "Moderate",
                                                        `Overall certainty` = "Low",
                                                        Balance = "Probably favours intervention"),
                                                 Q3 = c(`Desirable effects` = "Large",
                                                        `Undesirable effects` = "Small",
                                                        `Overall certainty` = "Moderate",
                                                        Balance = "Probably favours intervention")),
                   Recommendation = c(Q1 = "Immunocompetent adults aged over 50 years are recommended to receive Shingrix for the prevention of herpes zoster and associated complications",
                                      Q2 = "For immunocompetent adults aged over 50 years Shingrix is preferred over Zostavax for the prevention of herpes zoster and associated complications",
                                      Q3 = "Immunocompromised adults aged over 18 years are recommended to receive Shingrix for the prevention of herpes zoster and associated complications"))