dat_meningococcal <- list(Initiation = "Following ACIP recommendation of Meningococcal B vaccines",
                          Question = c(Q1 = "Should people at a standard risk of invasive meningococcal disease previously vaccinated with a Meningococcal B primary series receive a Bexsero booster vaccination?",
                                       Q2 = "Should people at an increased risk of invasive meningococcal disease previously vaccinated with a Meningococcal B primary series receive a Bexsero booster vaccination?",
                                       Q3 = "Should people at a standard risk of invasive meningococcal disease previously vaccinated with a Meningococcal B primary series receive a Trumenba booster vaccination?",
                                       Q4 = "Should people at an increased risk of invasive meningococcal disease previously vaccinated with a Meningococcal B primary series receive a Trumenba booster vaccination?"),
                          Population = c(Q1 = "Children 2 months - 2 years, adolescents and adults over 15 years",
                                         Q2 = "Children 2 months - 2 years, adolescents and adults over 15 years",
                                         Q3 = "Adolescents and adults over 15 years",
                                         Q4 = "Adolescents and adults over 15 years"),
                          Intervention = c(Q1 = "Bexsero booster dose",
                                           Q2 = "Bexsero booster dose",
                                           Q3 = "Trumenba booster dose",
                                           Q4 = "Trumenba booster dose"),
                          Comparator = c(Q1 = "Placebo/No vaccine/Alternative vaccine",
                                         Q2 = "Placebo/No vaccine/Alternative vaccine",
                                         Q3 = "Placebo/No vaccine/Alternative vaccine",
                                         Q4 = "Placebo/No vaccine/Alternative vaccine"),
                          Literature = c(Q1 = "7 observational studies",
                                         Q2 = "7 observational studies",
                                         Q3 = "1 observational study",
                                         Q4 = "1 observational study"),
                          Outcomes = list(Q1 = list(`Immunogenicity up to 1 month` =
                                                      list(`Risk of Bias` = c(Rating = "Serious", Reason = "Single arm comparison"),
                                                           Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                           Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                           Imprecision = c(Rating = "Serious", Reason = "Low number of events"),
                                                           Other = "None",
                                                           Certainty = "Low",
                                                           Direction = "Moderate benefit",
                                                           Importance = "Critical"),
                                                    `Immunogenicity up to 24 months` =
                                                      list(`Risk of Bias` = c(Rating = "Serious", Reason = "Single arm comparison"),
                                                           Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                           Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                           Imprecision = c(Rating = "Very serious", Reason = "Small sample size"),
                                                           Other = "None",
                                                           Certainty = "Very low",
                                                           Direction = "Moderate benefit",
                                                           Importance = "Critical"),
                                                    `Geometric mean ratio up to 1 month` =
                                                      list(`Risk of Bias` = c(Rating = "Serious", Reason = "Single arm comparison"),
                                                           Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                           Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                           Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                           Other = "None",
                                                           Certainty = "Low",
                                                           Direction = "Large benefit",
                                                           Importance = "Critical"),
                                                    `Local adverse events up to 7 days` =
                                                      list(`Risk of Bias` = c(Rating = "Serious", Reason = "Single arm comparison"),
                                                           Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                           Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                           Imprecision = c(Rating = "Serious", Reason = "Low number of events"),
                                                           Other = "None",
                                                           Certainty = "Low",
                                                           Direction = "Large cost",
                                                           Importance = "Important"),
                                                    `Systemic adverse events up to 7 days` =
                                                      list(`Risk of Bias` = c(Rating = "Serious", Reason = "Single arm comparison"),
                                                           Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                           Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                           Imprecision = c(Rating = "Serious", Reason = "Low number of events"),
                                                           Other = "None",
                                                           Certainty = "Low",
                                                           Direction = "Large cost",
                                                           Importance = "Important"),
                                                    `Unsolicited adverse events up to 7 days` =
                                                      list(`Risk of Bias` = c(Rating = "Serious", Reason = "Single arm comparison"),
                                                           Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                           Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                           Imprecision = c(Rating = "Serious", Reason = "Low number of events"),
                                                           Other = "None",
                                                           Certainty = "Low",
                                                           Direction = "Small cost",
                                                           Importance = "Important"),
                                                    `Fever up to 7 days` =
                                                      list(`Risk of Bias` = c(Rating = "Serious", Reason = "Single arm comparison"),
                                                           Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                           Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                           Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                           Other = "None",
                                                           Certainty = "Low",
                                                           Direction = "Small cost",
                                                           Importance = "Important")),
                                          Q2 = list(`Immunogenicity up to 1 month` =
                                                      list(`Risk of Bias` = c(Rating = "Serious", Reason = "Single arm comparison"),
                                                           Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                           Indirectness = c(Rating = "Serious", Reason = "No participants at an increased risk of invasive meningococcal disease included"),
                                                           Imprecision = c(Rating = "Serious", Reason = "Low number of events"),
                                                           Other = "None",
                                                           Certainty = "Very low",
                                                           Direction = "Moderate benefit",
                                                           Importance = "Critical"),
                                                    `Immunogenicity up to 24 months` =
                                                      list(`Risk of Bias` = c(Rating = "Serious", Reason = "Single arm comparison"),
                                                           Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                           Indirectness = c(Rating = "Serious", Reason = "No participants at an increased risk of invasive meningococcal disease included"),
                                                           Imprecision = c(Rating = "Very serious", Reason = "Small sample size"),
                                                           Other = "None",
                                                           Certainty = "Very low",
                                                           Direction = "Moderate benefit",
                                                           Importance = "Critical"),
                                                    `Geometric mean ratio up to 1 month` =
                                                      list(`Risk of Bias` = c(Rating = "Serious", Reason = "Single arm comparison"),
                                                           Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                           Indirectness = c(Rating = "Serious", Reason = "No participants at an increased risk of invasive meningococcal disease included"),
                                                           Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                           Other = "None",
                                                           Certainty = "Very low",
                                                           Direction = "Large benefit",
                                                           Importance = "Critical"),
                                                    `Local adverse events up to 7 days` =
                                                      list(`Risk of Bias` = c(Rating = "Serious", Reason = "Single arm comparison"),
                                                           Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                           Indirectness = c(Rating = "Serious", Reason = "No participants at an increased risk of invasive meningococcal disease included"),
                                                           Imprecision = c(Rating = "Serious", Reason = "Low number of events"),
                                                           Other = "None",
                                                           Certainty = "Very low",
                                                           Direction = "Large cost",
                                                           Importance = "Important"),
                                                    `Systemic adverse events up to 7 days` =
                                                      list(`Risk of Bias` = c(Rating = "Serious", Reason = "Single arm comparison"),
                                                           Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                           Indirectness = c(Rating = "Serious", Reason = "No participants at an increased risk of invasive meningococcal disease included"),
                                                           Imprecision = c(Rating = "Serious", Reason = "Low number of events"),
                                                           Other = "None",
                                                           Certainty = "Very low",
                                                           Direction = "Large cost",
                                                           Importance = "Important"),
                                                    `Unsolicited adverse events up to 7 days` =
                                                      list(`Risk of Bias` = c(Rating = "Serious", Reason = "Single arm comparison"),
                                                           Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                           Indirectness = c(Rating = "Serious", Reason = "No participants at an increased risk of invasive meningococcal disease included"),
                                                           Imprecision = c(Rating = "Serious", Reason = "Low number of events"),
                                                           Other = "None",
                                                           Certainty = "Very low",
                                                           Direction = "Small cost",
                                                           Importance = "Important"),
                                                    `Fever up to 7 days` =
                                                      list(`Risk of Bias` = c(Rating = "Serious", Reason = "Single arm comparison"),
                                                           Inconsistency = c(Rating = "Not serious", Reason = "None"),
                                                           Indirectness = c(Rating = "Serious", Reason = "No participants at an increased risk of invasive meningococcal disease included"),
                                                           Imprecision = c(Rating = "Serious", Reason = "Small sample size"),
                                                           Other = "None",
                                                           Certainty = "Very low",
                                                           Direction = "Small cost",
                                                           Importance = "Important")),
                                          Q3 = list(`Immunogenicity up to 1 month` =
                                                      list(`Risk of Bias` = c(Rating = "Serious", Reason = "Single arm comparison"),
                                                           Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                           Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                           Imprecision = c(Rating = "Very serious", Reason = "Low number of events"),
                                                           Other = "None",
                                                           Certainty = "Very low",
                                                           Direction = "Large benefit",
                                                           Importance = "Critical"),
                                                    `Immunogenicity up to 26 months` =
                                                      list(`Risk of Bias` = c(Rating = "Serious", Reason = "Single arm comparison"),
                                                           Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                           Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                           Imprecision = c(Rating = "Very serious", Reason = "Low number of events"),
                                                           Other = "None",
                                                           Certainty = "Very low",
                                                           Direction = "Moderate benefit",
                                                           Importance = "Critical"),
                                                    `Pain up to 7 days` =
                                                      list(`Risk of Bias` = c(Rating = "Serious", Reason = "Single arm comparison"),
                                                           Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                           Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                           Imprecision = c(Rating = "Very serious", Reason = "Low number of events"),
                                                           Other = "None",
                                                           Certainty = "Very low",
                                                           Direction = "Large cost",
                                                           Importance = "Important"),
                                                    `Fatigue up to 7 days` =
                                                      list(`Risk of Bias` = c(Rating = "Serious", Reason = "Single arm comparison"),
                                                           Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                           Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                           Imprecision = c(Rating = "Very serious", Reason = "Low number of events"),
                                                           Other = "None",
                                                           Certainty = "Very low",
                                                           Direction = "Large cost",
                                                           Importance = "Important"),
                                                    `Serious adverse events up to 7 days` =
                                                      list(`Risk of Bias` = c(Rating = "Serious", Reason = "Single arm comparison"),
                                                           Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                           Indirectness = c(Rating = "Not serious", Reason = "None"),
                                                           Imprecision = c(Rating = "Very serious", Reason = "Low number of events"),
                                                           Other = "None",
                                                           Certainty = "Very low",
                                                           Direction = "Moderate cost",
                                                           Importance = "Important")),
                                          Q4 = list(`Immunogenicity up to 1 month` =
                                                      list(`Risk of Bias` = c(Rating = "Serious", Reason = "Single arm comparison"),
                                                           Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                           Indirectness = c(Rating = "Serious", Reason = "No participants at an increased risk of invasive meningococcal disease included"),
                                                           Imprecision = c(Rating = "Very serious", Reason = "Low number of events"),
                                                           Other = "None",
                                                           Certainty = "Very low",
                                                           Direction = "Large benefit",
                                                           Importance = "Critical"),
                                                    `Immunogenicity up to 26 months` =
                                                      list(`Risk of Bias` = c(Rating = "Serious", Reason = "Single arm comparison"),
                                                           Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                           Indirectness = c(Rating = "Serious", Reason = "No participants at an increased risk of invasive meningococcal disease included"),
                                                           Imprecision = c(Rating = "Very serious", Reason = "Low number of events"),
                                                           Other = "None",
                                                           Certainty = "Very low",
                                                           Direction = "Moderate benefit",
                                                           Importance = "Critical"),
                                                    `Pain up to 7 days` =
                                                      list(`Risk of Bias` = c(Rating = "Serious", Reason = "Single arm comparison"),
                                                           Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                           Indirectness = c(Rating = "Serious", Reason = "No participants at an increased risk of invasive meningococcal disease included"),
                                                           Imprecision = c(Rating = "Very serious", Reason = "Low number of events"),
                                                           Other = "None",
                                                           Certainty = "Very low",
                                                           Direction = "Large cost",
                                                           Importance = "Important"),
                                                    `Fatigue up to 7 days` =
                                                      list(`Risk of Bias` = c(Rating = "Serious", Reason = "Single arm comparison"),
                                                           Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                           Indirectness = c(Rating = "Serious", Reason = "No participants at an increased risk of invasive meningococcal disease included"),
                                                           Imprecision = c(Rating = "Very serious", Reason = "Low number of events"),
                                                           Other = "None",
                                                           Certainty = "Very low",
                                                           Direction = "Large cost",
                                                           Importance = "Important"),
                                                    `Serious adverse events up to 7 days` =
                                                      list(`Risk of Bias` = c(Rating = "Serious", Reason = "Single arm comparison"),
                                                           Inconsistency = c(Rating = "Not assessed", Reason = "Only one study included"),
                                                           Indirectness = c(Rating = "Serious", Reason = "No participants at an increased risk of invasive meningococcal disease included"),
                                                           Imprecision = c(Rating = "Very serious", Reason = "Low number of events"),
                                                           Other = "None",
                                                           Certainty = "Very low",
                                                           Direction = "Moderate cost",
                                                           Importance = "Important"))),
                          `Evidence to decision` = list(Q1 = c(`Desirable effects` = "Moderate",
                                                               `Undesirable effects` = "Small",
                                                               `Overall certainty` = "Low",
                                                                Balance = "Probably favours intervention"),
                                                        Q2 = c(`Desirable effects` = "Moderate",
                                                               `Undesirable effects` = "Small",
                                                               `Overall certainty` = "Very low",
                                                               Balance = "Favours intervention"),
                                                        Q3 = c(`Desirable effects` = "Moderate",
                                                               `Undesirable effects` = "Small",
                                                               `Overall certainty` = "Very low",
                                                               Balance = "Probably favours intervention"),
                                                        Q4 = c(`Desirable effects` = "Moderate",
                                                               `Undesirable effects` = "Small",
                                                               `Overall certainty` = "Very low",
                                                               Balance = "Favours intervention")),
                    Recommendation = c(Q1 = "Meningococcal B booster doses in individuals at standard background risk of invasive meningococcal disease are not recommended for individuals of any age",
                                       Q2 = "Individuals of all ages at risk of invasive meningococcal disease are recommended to receive a single booster dose of Bexsero",
                                       Q3 = "Meningococcal B booster doses in individuals at standard background risk of invasive meningococcal disease are not recommended for individuals of any age",
                                       Q4 = "Individuals of all ages at risk of invasive meningococcal disease are recommended to receive a single booster dose of Trumenba"))